# Generated by Django 2.2.2 on 2021-11-24 03:00

import accounts.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.MyUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateField(default=datetime.date(2021, 11, 24), verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='入力されたメールアドレスに確認メールが送信されます。', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(error_messages={'unique': 'A user with that user_id already exists.'}, help_text='ユーザーIDは一意です。英数字と_(アンダースコア)のみが使用できます。', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3, '3文字以上です！'), django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$', '英数字と_(アンダースコア)のみです！')], verbose_name='ユーザーID'),
        ),
    ]
